name: CapsFilter
version: '${project.version}'
main: com.savage.plugins.capsfilter.CapsFilter
api-version: 1.19
authors: [ SavageDev ]
commands:
  reloadfilter:
    aliases: rfilter
    description: reloads config file for chat filter
    permission: profile.reloadfilter
