#============================================================================#
# _________ .__            __    ___________.__.__   __                      #
# \_   ___ \|  |__ _____ _/  |_  \_   _____/|__|  |_/  |_  ___________       #
#  /    \  \/|  |  \\__  \\   __\  |    __)  |  |  |\   __\/ __ \_  __ \     #
# \     \___|   Y  \/ __ \|  |    |     \   |  |  |_|  | \  ___/|  | \/      #
#  \______  /___|  (____  /__|    \___  /   |__|____/__|  \___  >__|         #
#  \/     \/     \/            \/                      \/                    #
#============================================================================#

max-caps-amount: 15